# Generated by Django 6.0 on 2026-01-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedbacks',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
