# Generated by Django 6.0 on 2026-01-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedback_table_alter_question_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
        migrations.AddField(
            model_name='feedback',
            name='answers',
            field=models.JSONField(null=True),
        ),
    ]
