# Generated by Django 6.0 on 2026-01-17 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_date_joined_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 17, 20, 43, 44, 343812, tzinfo=datetime.timezone.utc)),
        ),
    ]
