# Generated by Django 6.0 on 2026-02-03 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 3, 17, 50, 24, 402550, tzinfo=datetime.timezone.utc)),
        ),
    ]
