# Generated by Django 6.0 on 2026-01-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree_programs',
            field=models.JSONField(default=list),
        ),
    ]
